# Generated by Django 3.2.11 on 2022-01-08 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='users',
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='currency',
            name='wallets',
            field=models.ManyToManyField(blank=True, related_name='currency', to='api.Wallet'),
        ),
    ]
