# Generated by Django 3.2.11 on 2022-01-08 08:16

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220108_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='after_receiver_amount_snapshot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='after_sender_amount_snapshot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='before_receiver_amount_snapshot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='before_sender_amount_snapshot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=api.models.pfp_path),
        ),
    ]
