# Generated by Django 3.2.11 on 2022-01-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220108_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='privatekey',
        ),
        migrations.RemoveField(
            model_name='user',
            name='publickey',
        ),
        migrations.AddField(
            model_name='wallet',
            name='privatekey',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='publickey',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
