# Generated by Django 3.2.11 on 2022-01-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220109_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_signature',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_signature',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
