# Generated by Django 3.2.11 on 2022-01-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220109_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='initial_balance',
            field=models.IntegerField(default=0),
        ),
    ]
